name: ketchup_ui
description: "番茄汁UI,基于拼接大屏生态的基础UI库,解决大屏适配问题,另有 *-assets-kit 和 *-game-kit 系列工具解决大屏资源素材 和 大屏游戏交互框架的问题"
version: 1.0.0
homepage: https://ketchupui.github.io
repository: https://github.com/ketchupui/ketchup_ui

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  go_router: ^14.6.3
  vector_math: ^2.2.0

  flutter:
    sdk: flutter
  collection: ^1.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
